/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author Aybar
 */
public class Panel extends JPanel {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPago = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jPanelPago = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jSpinner2 = new javax.swing.JSpinner();

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconos/monto.png"))); // NOI18N
        jLabel1.setText("Monto");

        jFormattedTextField1.setColumns(25);
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jFormattedTextField1.setToolTipText("Monto minimo: 500.00 DOP");
        jFormattedTextField1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jFormattedTextField1.setName(""); // NOI18N
        jFormattedTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField1PropertyChange(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconos/interes.png"))); // NOI18N
        jLabel2.setText("Interes");

        btnContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconos/continuar.png"))); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.setToolTipText("");
        btnContinuar.setName(""); // NOI18N
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconos/per cent.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/iconos/plazo.png"))); // NOI18N
        jLabel5.setText("Plazo");

        jSpinner1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 60, 1));
        jSpinner1.setValue(12);

        jLabel6.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        jLabel6.setText("Mes(es)");

        jPanelPago.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Forma de pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 0, 14))); // NOI18N

        buttonGroupPago.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jRadioButton1.setText("Cuota fija");

        buttonGroupPago.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jRadioButton2.setText("Capital fijo");

        buttonGroupPago.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Plan de pago irregular");

        javax.swing.GroupLayout jPanelPagoLayout = new javax.swing.GroupLayout(jPanelPago);
        jPanelPago.setLayout(jPanelPagoLayout);
        jPanelPagoLayout.setHorizontalGroup(
            jPanelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPagoLayout.setVerticalGroup(
            jPanelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jSpinner2.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(24.0d, 0.009999999776482582d, 100.0d, 0.5d));
        jSpinner2.setValue(24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnContinuar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6))
                                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jPanelPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 151, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jPanelPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Muestra un mensaje de confirmacion cuando cumple el monto minimo
    private void confirmarDatos(){
        
        final double capital = (((Number)jFormattedTextField1.getValue()).doubleValue()); // Monto solicitado
        
        final boolean esCapitalSuficiente = capital >= 500; // Monto minimo a solicitar
        
        final double TASA_NOMINAL = (((Number)jSpinner2.getValue()).byteValue());
        
        java.text.DecimalFormat formato = new java.text.DecimalFormat("#,##0.00"); // Separa centenas por coma. Ejemplo: 100,000.94
        
        byte plazo = (((Number)jSpinner1.getValue()).byteValue());
        
        if (esCapitalSuficiente){
            String mensaje = "Monto: " + formato.format(capital) + " RD$."
                        + "\n\n Tasa de interes: " + formato.format(TASA_NOMINAL) + " %"
                        + "\n\nPlazo: " + plazo + " mes(es).";
                
            int answer = javax.swing.JOptionPane.showConfirmDialog(Panel.this, 
                        mensaje, "Confirmacion", 
                        javax.swing.JOptionPane.OK_CANCEL_OPTION, 
                        javax.swing.JOptionPane.QUESTION_MESSAGE);
                
            if (answer == JOptionPane.OK_OPTION){
                    
                    String boton; // Para saber cual de los 3 botones es presionado
                    
                    // Evalua cual de los 3 botones es seleccionado.
                    if (jRadioButton1.isSelected()){
                        // boton = "Cuota Fija".
                        boton = jRadioButton1.getActionCommand();
                    } else if (jRadioButton2.isSelected()){
                        // boton = "Capital fijo".
                        boton = jRadioButton2.getActionCommand();
                    } else{
                        // boton = "Plan Irregular"
                        boton = jRadioButton3.getActionCommand();
                    }
                    
                    //-------------------------------------------------------------                    
                        java.awt.EventQueue.invokeLater(() -> {                       
                        new PanelResultado(capital, TASA_NOMINAL, plazo, boton).setVisible(true); // Abre tabla de amortizacion
                        });  
                }
            
            } else{
                throw new RuntimeException();
            }
    }
       
    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        try {
            confirmarDatos();
        } catch (RuntimeException e){
            javax.swing.JOptionPane.showMessageDialog(Panel.this, 
                    "MONTO debe ser desde 500 RD$.", 
                    "Cantidad insuficiente", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
                         
    }//GEN-LAST:event_btnContinuarActionPerformed

    // Funcionalidad extra al jFormattedTextField (nada importante).
    private void jFormattedTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField1PropertyChange
        // && jFormattedTextField1.isEditValid() && !jFormattedTextField1.hasFocus()
        if (jFormattedTextField1.getValue() != null){
            double capital = Math.abs(((Number)jFormattedTextField1.getValue()).doubleValue());
            jFormattedTextField1.setValue(capital);
            jFormattedTextField1.setBackground((capital < 500)? Color.RED: Color.WHITE);
        }    
    }//GEN-LAST:event_jFormattedTextField1PropertyChange
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.ButtonGroup buttonGroupPago;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelPago;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    // End of variables declaration//GEN-END:variables
}
