/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main;

import javax.swing.JOptionPane;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.time.LocalDate;

/**
 *
 * @author Manuel Garcia
 */
public class PanelResultado extends javax.swing.JFrame {

    /**
     * Creates new form PanelResultado
     */
    
    private final javax.swing.table.DefaultTableModel modelo;
    private BufferedWriter escribe;
    private boolean principio; 
    
    public PanelResultado(double p, double j, byte t, String boton) {
        initComponents();
        // p = monto solicitado     j = tasa nominal    t = plazo
        modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        principio = true;
        try {

            amortizar(p, j, t, boton); // Los datos,
            if (escribe != null){
                escribe.close();
            }
        } catch (IOException ex) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_Fecha = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_Monto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_Interes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_Financiados = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_Comision = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_Desembolso = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel_Cuota = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_Gracia = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel_Periodo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel_Inicial = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel_Gastos = new javax.swing.JLabel();
        jLabel_TotalCuotas = new javax.swing.JLabel();
        jLabel_TotalCapital = new javax.swing.JLabel();
        jLabel_TotalInteres = new javax.swing.JLabel();
        jLabel_TotalComision = new javax.swing.JLabel();
        jLabel_TotalGastos = new javax.swing.JLabel();
        jLabel_Total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Plan de pagos");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("iconos/table row.png"))
        );

        jScrollPane1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N

        jTable1.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Cuota", "Fecha", "Saldo", "Capital", "Interes", "Comision", "Gastos", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Byte.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Negociar Plan de Pago");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Cliente:");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Fecha:");

        jLabel_Fecha.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel_Fecha.setText("04/05/2017");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Monto solicitado:");

        jLabel_Monto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel_Monto.setText("RD$100,000.00");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Interes:");

        jLabel_Interes.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel_Interes.setText("24.00 %");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Gastos financiados:");

        jLabel_Financiados.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel_Financiados.setText("0.00");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Comision:");

        jLabel_Comision.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel_Comision.setText("0.00 %");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setText("Gastos desembolso:");

        jLabel_Desembolso.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel_Desembolso.setText("0.00");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("Gastos cuota:");

        jLabel_Cuota.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel_Cuota.setText("0.00");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setText("Tipo gracia:");

        jLabel_Gracia.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel_Gracia.setText("0 - NO GRACIA");

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setText("Periodo:");

        jLabel_Periodo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel_Periodo.setText("0");

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setText("Monto Inicial:");

        jLabel_Inicial.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel_Inicial.setText("0.00");

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setText("Total gastos:");

        jLabel_Gastos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel_Gastos.setText("0.00");

        jLabel_TotalCuotas.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel_TotalCuotas.setText("12 Cuota(s)");

        jLabel_TotalCapital.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel_TotalCapital.setText("100,000.00");

        jLabel_TotalInteres.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel_TotalInteres.setText("13,471.53");

        jLabel_TotalComision.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel_TotalComision.setText("0.00");

        jLabel_TotalGastos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel_TotalGastos.setText("0.00");

        jLabel_Total.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel_Total.setText("113,471.53");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_Fecha)
                                            .addComponent(jLabel_Monto)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel_Interes)
                                                .addGap(155, 155, 155)
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel_Comision))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Financiados)
                                .addGap(104, 104, 104)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Desembolso)))
                        .addGap(57, 57, 57)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Cuota)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Gastos)
                                    .addComponent(jLabel_Gracia)
                                    .addComponent(jLabel_Periodo)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Inicial)
                                .addGap(69, 69, 69)))
                        .addGap(0, 43, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel_TotalCuotas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_TotalCapital)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel_TotalInteres)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel_TotalComision)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel_TotalGastos)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel_Total)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel_Fecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel_Monto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel_Interes))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jLabel_Comision))
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel_Financiados)
                            .addComponent(jLabel_Desembolso)
                            .addComponent(jLabel9)
                            .addComponent(jLabel_Cuota)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel_Gracia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel_Periodo))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel_Inicial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel_Gastos))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TotalCuotas)
                    .addComponent(jLabel_TotalCapital)
                    .addComponent(jLabel_TotalInteres)
                    .addComponent(jLabel_TotalComision)
                    .addComponent(jLabel_TotalGastos)
                    .addComponent(jLabel_Total))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private class Run implements Runnable{

        @Override
        public void run() {
            JOptionPane.showMessageDialog(null, "La informacion se ha guardado correctamente.", "Archivo guardado", 
                    JOptionPane.INFORMATION_MESSAGE);                    
        }
        
    }
    
    private void leerArchivo(File archivo){
        try (BufferedReader lee = new BufferedReader(new FileReader(archivo))){
            do{
                String linea = lee.readLine();
                if (linea == null){
                    break;
                }
                System.out.println(linea);
            } while (true);
        } catch (IOException e){
            
        }
    }

    private void escribirArchivo(String linea, File archivo) throws IOException{
        if (principio){
            if (!archivo.exists()){
                archivo.createNewFile();
            }
            escribe = new BufferedWriter(new FileWriter(archivo));
            principio = false;
            escribirArchivo("No. Cuota| Fecha      | Saldo      |"
                      + " Capital  | Interes  | Gastos| Comision|"
                      + " Total", archivo);
            escribe.write(linea);
            escribe.newLine();            
        } else {
            escribe.write(linea);
            escribe.newLine();            
        }
    }
    
    
    private void llenarTabla(Object [] datos, File archivo) throws IOException {
        
        String linea = datos[0].toString() + "       | " + datos[1].toString() + " | " 
                         + datos[2].toString() + " | " + datos[3].toString() + " | "
                         + datos[4].toString() + " | " + datos[5].toString() + "   | "
                         + datos[6].toString() + "    | " + datos[7].toString();

         escribirArchivo(linea, archivo);

         modelo.addRow(datos);
    }
   
    // Metodo generico encargado de iniciar la amortizacion.
    private void amortizar(double p, double j, byte t, String boton) throws IOException{
        // j = tasa nominal
        // p = capital
        // t = plazo 
        final byte m = 12; // Frecuencia que se capitaliza la tasa en un año.
        final double TASA_INTERES = j / 100 / m; // Interes mensual.
        double intereses = p * TASA_INTERES;  // Interes generados del mes
        
        LocalDate fechaActual = LocalDate.now(); 
        jLabel_Fecha.setText(fechaActual.toString());
        
        java.text.DecimalFormat formato = new java.text.DecimalFormat("#,##0.00");
        
        jLabel_Monto.setText("RD$ " + formato.format(p)); // Ej: RD$ 100,000.00 
        jLabel_Interes.setText(formato.format(j) + " %");

        if (boton.equalsIgnoreCase("Cuota Fija")){
            mostrarCuotaFija(new File("Cuota Fija.txt"), fechaActual,p, TASA_INTERES,
                    intereses,t);
        } else if (boton.equalsIgnoreCase("Capital Fijo")){
            mostrarCapitalFijo(new File("Capital Fijo.txt"), fechaActual, p, TASA_INTERES, intereses, t);
        } else {
            double cuota = Double.parseDouble(javax.swing.JOptionPane.showInputDialog(PanelResultado.this, 
                   "Ingrese nueva cuota fija", "Cuota fija", JOptionPane.QUESTION_MESSAGE));
           if (cuota > 0){
               mostrarPlanIrregular(new File("Plan Irregular.txt"), fechaActual, p, TASA_INTERES, 
                                    intereses, cuota);
           }

        }
        new Thread(new Run()).start();

    }

    // Calcular por amortizacion fija.
    private void mostrarCapitalFijo(File archivo, LocalDate fechaActual, double p,
                                    final double TASA_INTERES, double intereses, byte t) throws IOException{
        // p = capital
        // t = plazo         
        final double CAPITAL = p / t;
        double [] total = {0.00, 0.00, 0.00}; // Guarda sumatoria de capital, interes y cuota.
                       
        java.text.DecimalFormat formato = new java.text.DecimalFormat("#,##0.00");// Separa los numeros de JTable, ej: 100,000.00 
        
        jLabel_TotalCuotas.setText(t + " Cuota(s)");

        // Llena y guarda la tabla con los calculos generados
        // No. Cuota | Fecha    | Saldo   | Capital | Interes | Gastos  | Comision | Total
        // datos [0] | datos[1] | datos[2]| datos[3]| datos[4]| datos[5]| datos[6] | datos[7]
        for (int i = 1; i <= t; ++i){
            @SuppressWarnings("LocalVariableHidesMemberVariable")
            double cuota = CAPITAL + intereses;
            Object [] datos = {i, fechaActual.plusMonths(i), formato.format(p), 
                formato.format(CAPITAL), formato.format(intereses), formato.format(0),
                formato.format(0), formato.format(cuota)};
            
            total[0] += CAPITAL; // Sumatoria de capital
            total[1] += intereses; // Sumatoria de intereses
            total[2] += cuota;      // Sumatoria de cuota
            p -= CAPITAL;
            intereses = p * TASA_INTERES;
            llenarTabla(datos, archivo);           
        }

        // Muestra el total a pagar de: capital, interes y cuota;
        jLabel_TotalCapital.setText(formato.format(total[0]));
        jLabel_TotalInteres.setText(formato.format(total[1]));
        jLabel_Total.setText(formato.format(total[2]));
        try {
            escribe.close();
        } catch (IOException ex) {
            Logger.getLogger(PanelResultado.class.getName()).log(Level.SEVERE, null, ex);
        }
        leerArchivo(archivo); 
    }
    
    //Calcular pago irregular
    private void mostrarPlanIrregular(File archivo, LocalDate fechaActual, double p,
                                    final double TASA_INTERES, double intereses, double cuota) throws IOException{
        // j = tasa nominal
        // p = capital
        // t = plazo 
        double x = - (Math.log(1 - (intereses)/cuota)) / Math.log(1 + TASA_INTERES); // Formula plazo.
        int t = (int)Math.round(x); 
        double capital = cuota - intereses;	

        double [] total = {0.00, 0.00, 0.00}; // Guarda sumatoria de capital, interes y cuota.
        
        jLabel_TotalCuotas.setText(t + " Cuota(s)");
        java.text.DecimalFormat formato = new java.text.DecimalFormat("#,##0.00");
        

        // Llena la tabla con los calculos generados
        // No. Cuota | Fecha | Saldo | Capital | Interes | Gastos | Comision | Total
        for (int i = 1; i <= t; ++i){
            if (p < capital){
                capital = p;
                cuota = capital + intereses;
            }
            Object [] datos = {i, fechaActual.plusMonths(i), formato.format(p), 
                formato.format(capital), formato.format(intereses), formato.format(0),
                formato.format(0), formato.format(cuota)}; // Datos dentro de nuestro JTable

            llenarTabla(datos, archivo);
            total[0] += capital;
            total[1] += intereses;
            total[2] += cuota;
            
            p = p - capital;
            capital = cuota - intereses;
            intereses = p * TASA_INTERES;

         
        }
        // Muestra el total a pagar de: capital, interes y cuota;
        jLabel_TotalCapital.setText(formato.format(total[0]));
        jLabel_TotalInteres.setText(formato.format(total[1]));
        jLabel_Total.setText(formato.format(total[2]));
        try {
            if (escribe != null){
                escribe.close();
            }
        } catch (IOException ex) {
            Logger.getLogger(PanelResultado.class.getName()).log(Level.SEVERE, null, ex);
        }
        leerArchivo(archivo);
        
    }
    
    // Calcular cuota fija
    private void mostrarCuotaFija(File archivo, LocalDate fechaActual, double p,
                                    final double TASA_INTERES, double intereses, byte t) throws IOException{
        // p = capital
        // t = plazo 
        final byte m = 12; // Frecuencia que se capitaliza la tasa en un año.
        final double n = m * t/12; // Numero de capitalización por tiempo transcurrido.
        
	final double CUOTA = intereses / (1 - Math.pow(1+TASA_INTERES, -n) ); // Formula fija.
        double capital = CUOTA - intereses;
        
        double [] total = {0.00, 0.00, 0.00}; // Guarda sumatoria de capital, interes y cuota.
                
        java.text.DecimalFormat formato = new java.text.DecimalFormat("#,##0.00");
        
        jLabel_TotalCuotas.setText(t + " Cuota(s)");


        // Llena la tabla con los calculos generados
        // No. Cuota | Fecha | Saldo | Capital | Interes | Gastos | Comision | Total
        for (int i = 1; i <= t; ++i){
            Object [] datos = {i, fechaActual.plusMonths(i), formato.format(p), 
                formato.format(capital), formato.format(intereses), formato.format(0),
                formato.format(0), formato.format(CUOTA)};
            //linea = new StringBuilder(datos [0] + datos [1] + datos[2]);
            total[0] += capital;
            total[1] += intereses;
            total[2] += CUOTA;
            p = p - capital;
            intereses = p * TASA_INTERES;
            capital = CUOTA - intereses;
            llenarTabla(datos, archivo);
           
        }

        // Muestra el total a pagar de: capital, interes y cuota;
        jLabel_TotalCapital.setText(formato.format(total[0]));
        jLabel_TotalInteres.setText(formato.format(total[1]));
        jLabel_Total.setText(formato.format(total[2]));
        try {
            escribe.close();
        } catch (IOException ex) {
            Logger.getLogger(PanelResultado.class.getName()).log(Level.SEVERE, null, ex);
        }
        leerArchivo(archivo);
    
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Comision;
    private javax.swing.JLabel jLabel_Cuota;
    private javax.swing.JLabel jLabel_Desembolso;
    private javax.swing.JLabel jLabel_Fecha;
    private javax.swing.JLabel jLabel_Financiados;
    private javax.swing.JLabel jLabel_Gastos;
    private javax.swing.JLabel jLabel_Gracia;
    private javax.swing.JLabel jLabel_Inicial;
    private javax.swing.JLabel jLabel_Interes;
    private javax.swing.JLabel jLabel_Monto;
    private javax.swing.JLabel jLabel_Periodo;
    private javax.swing.JLabel jLabel_Total;
    private javax.swing.JLabel jLabel_TotalCapital;
    private javax.swing.JLabel jLabel_TotalComision;
    private javax.swing.JLabel jLabel_TotalCuotas;
    private javax.swing.JLabel jLabel_TotalGastos;
    private javax.swing.JLabel jLabel_TotalInteres;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
